import random

problems = [
    "1. Print 'Hello, World!' with a user-provided name.",
    "2. Return the sum of two integers.",
    "3. Given two numbers, return their sum, difference, product, and quotient.",
    "4. Check if an integer is even.",
    "5. Find the minimum and maximum of three numbers.",
    "6. Count digits, letters, and spaces in a string.",
    "7. Reverse a given string without built-in reverse functions.",
    "8. Convert a string to uppercase, lowercase, and title case.",
    "9. Check if a given string is a palindrome.",
    "10. Count the frequency of each character in a string.",
    "11. Print the multiplication table of a given integer.",
    "12. Generate the first N Fibonacci numbers.",
    "13. Compute the factorial of a number.",
    "14. Check if a number is prime.",
    "15. Compute the sum of digits of a number.",
    "16. Reverse an integer’s digits.",
    "17. Compute the average of a list of numbers.",
    "18. Simple string compression (e.g., 'aaabbc' -> 'a3b2c1').",
    "19. Sort a list of integers without using the built-in sort function.",
    "20. Remove duplicates from a list.",
    "21. Implement the Collatz sequence for a given integer.",
    "22. Implement a Caesar cipher shift for a string.",
    "23. Find the longest word in a sentence.",
    "24. Rotate an array by a given number of steps.",
    "25. Merge two sorted lists into a single sorted list without using built-in sort.",
    "26. Count vowels and consonants in a string.",
    "27. Add two matrices.",
    "28. Transpose a matrix.",
    "29. Check if two strings are anagrams.",
    "30. Find the GCD and LCM of two numbers.",
    "31. Generate all permutations of a small set of characters.",
    "32. Print the first N rows of Pascal’s triangle.",
    "33. Convert a small integer (0-999) into words.",
    "34. Remove stopwords from a sentence.",
    "35. Print a histogram from a list of integers.",
    "36. Run-length encode a string.",
    "37. Check if parentheses/brackets are balanced.",
    "38. Implement a Sieve of Eratosthenes to find all primes up to N.",
    "39. Check if one string is a rotation of another.",
    "40. Print a 2D matrix in spiral order.",
    "41. Validate Sudoku rows/columns partially.",
    "42. Parse a CSV-like string and produce summary data.",
    "43. Justify text to a given width.",
    "44. Convert an infix arithmetic expression to postfix notation.",
    "45. Find a path through a maze using brute force (backtracking).",
    "46. Normalize various date string formats.",
    "47. Merge overlapping intervals.",
    "48. Count inversions in a list (naive).",
    "49. Find the longest common substring between two strings (naive).",
    "50. Convert a numeric string to an integer manually.",
    "51. Remove all occurrences of a substring from a string.",
    "52. Count how many times a substring appears in a string.",
    "53. Replace multiple spaces in a string with a single space.",
    "54. Find the second largest number in a list.",
    "55. Implement a basic command-line calculator (add, sub, mul, div).",
    "56. Check if a number is a perfect number.",
    "57. Print a star pattern (pyramid, diamond, etc.).",
    "58. Reverse the words in a sentence.",
    "59. Remove duplicates from a list of words, preserving order.",
    "60. Check if a list is a palindrome.",
    "61. Compute the nth harmonic number.",
    "62. Find the median of a list of numbers.",
    "63. Flatten a nested list.",
    "64. Convert a decimal number to binary.",
    "65. Convert a binary string to decimal.",
    "66. Count the frequency of each word in a sentence.",
    "67. Capitalize the first letter of each word in a sentence.",
    "68. Print a list of squares of numbers up to N.",
    "69. Check if a year is a leap year.",
    "70. Find the first non-repeating character in a string.",
    "71. Compute compound interest for given principal, rate, and time.",
    "72. Implement a unit conversion (e.g., Celsius to Fahrenheit).",
    "73. Sum all even numbers in a list.",
    "74. Sum all odd numbers in a list.",
    "75. Remove all punctuation from a string.",
    "76. Perform prime factorization of a number.",
    "77. Find the frequency of each digit in an integer.",
    "78. Check if a string has all unique characters.",
    "79. Remove all digits from a string.",
    "80. Replace all occurrences of a character in a string with another.",
    "81. Rotate a list until a certain element is at the front.",
    "82. Reverse each word in a sentence individually.",
    "83. Find the index of the first occurrence of a substring in a string.",
    "84. Generate a deterministic 'random' password of a given length.",
    "85. Check if two lists have the same elements in any order.",
    "86. Filter a list of dictionaries by a certain key-value pair.",
    "87. Find the longest increasing subsequence (naive).",
    "88. Count trailing zeros in the factorial of a given number.",
    "89. Separate even and odd numbers from a list into two lists.",
    "90. Compare a guessed number to a secret number (logic only).",
    "91. Compute the dot product of two vectors.",
    "92. Simple pattern matching (with '?' and '*').",
    "93. Shuffle a list deterministically.",
    "94. Validate an email address format.",
    "95. Find the longest palindromic substring (naive).",
    "96. Implement a Caesar cipher decoder.",
    "97. Sort a list of (name, age) tuples by age without built-in sort.",
    "98. Check if a number can be expressed as the sum of two squares.",
    "99. Remove duplicate characters from a string.",
    "100. Check if a large number (represented as a string) is divisible by 3."
]

def get_random_problem():
    return random.choice(problems)

if __name__ == "__main__":
    chosen_problem = get_random_problem()
    print("Your random problem is:")
    print(chosen_problem)
